// Code generated by codegen. DO NOT EDIT.
// Generated at: 2026-03-31T02:47:09+08:00

package agent_test

import (
	"ai/config"
	"ai/pkg/llm"
	"ai/pkg/logger"
	"ai/pkg/orchestrator"
	internalproto "ai/pkg/protocol"
	internaltm "ai/pkg/taskmanager"
	"ai/pkg/tools"
	"context"
	"fmt"
	"strings"
	"time"
)

const (
	AgentTestWorkflowID = "agent_test-default"
	AgentTestWorkflowWorkerID = "agent_test_worker"
	AgentTestDefaultTaskType = "agent_test_default"
)

type ctxKeyTaskManager struct{}

type Agent struct {
	orchestratorEngine orchestrator.Engine
	llmClient          *llm.Client
	chatModel          string
	TavilyTool tools.Tool
	AmapTool tools.Tool
	AgentInfoTool tools.Tool
	JinaReaderTool tools.Tool
}

type workflowNodeWorker struct {
	agent *Agent
}

type stepReporter struct {
	agent string
	taskID string
	manager internaltm.Manager
}

func NewAgent() (*Agent, error) {
	cfg := config.GetMainConfig()
	agent := &Agent{}

	agent.llmClient = llm.NewClient(cfg.LLM.URL, cfg.LLM.APIKey)
	agent.chatModel = strings.TrimSpace(cfg.LLM.ChatModel)
	if agent.chatModel == "" {
		agent.chatModel = strings.TrimSpace(cfg.LLM.ReasoningModel)
	}
	if agent.chatModel == "" {
		agent.chatModel = "qwen3-235b-a22b"
	}
	logger.Infof("[TRACE] agent_test llm_config url=%s model=%s api_key_set=%t", strings.TrimSpace(cfg.LLM.URL), agent.chatModel, strings.TrimSpace(cfg.LLM.APIKey) != "")

	TavilyToolConfig := tools.HTTPToolConfig{
		Method: "POST",
		URL: "https://api.tavily.com/search",
		Timeout: time.Duration(30) * time.Second,
	}
	TavilyToolConfig.Headers = map[string]string{
		"Content-Type": "application/json",
		"Authorization": "Bearer {{api_key}}",
	}
	TavilyToolConfig.BodyTemplate = "{\"query\":\"{{query}}\",\"search_depth\":\"{{search_depth}}\",\"max_results\":{{max_results}}}"
	agent.TavilyTool = tools.NewHTTPTool("tavily", "调用 Tavily 搜索 API 进行实时检索", []tools.ToolParameter{{Name: "api_key", Type: tools.ParamTypeString, Required: true, Description: "Tavily API Key"},{Name: "query", Type: tools.ParamTypeString, Required: true, Description: "检索关键词"},{Name: "search_depth", Type: tools.ParamTypeString, Required: false, Description: "检索深度，可选 basic/advanced"},{Name: "max_results", Type: tools.ParamTypeNumber, Required: false, Description: "返回结果数量上限"},}, TavilyToolConfig)
	AmapToolConfig := tools.MCPToolConfig{
		ServerURL: "https://mcp.amap.com/sse?key=603b7b141042d9e7418bd3617c1758c2",
		ToolName: "auto",
	}
	agent.AmapTool = tools.NewMCPTool("amap", "调用 AMap MCP 服务；由 Agent 通过 tool_name 决定具体子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 MCP 子工具名（如 maps_direction_driving）"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "MCP 子工具参数对象；优先使用此字段作为调用参数"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，将 query 等普通参数直接透传"},}, AmapToolConfig)
	AgentInfoToolConfig := tools.HTTPToolConfig{
		Method: "GET",
		URL: "http://127.0.0.1:8080/v1/orchestrator/agents",
		Timeout: time.Duration(30) * time.Second,
	}
	agent.AgentInfoTool = tools.NewHTTPTool("agent_info", "查询当前系统可用的 Agent 列表与能力说明", []tools.ToolParameter{}, AgentInfoToolConfig)
	JinaReaderToolConfig := tools.HTTPToolConfig{
		Method: "GET",
		URL: "https://r.jina.ai/{{url}}",
		Timeout: time.Duration(60) * time.Second,
	}
	agent.JinaReaderTool = tools.NewHTTPTool("jina_reader", "通过 Jina Reader 拉取并清洗网页正文内容", []tools.ToolParameter{{Name: "url", Type: tools.ParamTypeString, Required: true, Description: "需要读取的网页地址（http/https）"},}, JinaReaderToolConfig)

	engineCfg := orchestrator.Config{
		DefaultTaskTimeoutSec: cfg.Orchestrator.DefaultTaskTimeoutSec,
		RetryMaxAttempts:      cfg.Orchestrator.Retry.MaxAttempts,
		RetryBaseBackoffMs:    cfg.Orchestrator.Retry.BaseBackoffMs,
		RetryMaxBackoffMs:     cfg.Orchestrator.Retry.MaxBackoffMs,
	}
	if engineCfg.DefaultTaskTimeoutSec <= 0 {
		engineCfg.DefaultTaskTimeoutSec = 600
	}
	if engineCfg.RetryMaxAttempts <= 0 {
		engineCfg.RetryMaxAttempts = 3
	}
	if engineCfg.RetryBaseBackoffMs <= 0 {
		engineCfg.RetryBaseBackoffMs = 200
	}
	if engineCfg.RetryMaxBackoffMs <= 0 {
		engineCfg.RetryMaxBackoffMs = 5000
	}

	agent.orchestratorEngine = orchestrator.NewEngine(engineCfg, orchestrator.NewInMemoryAgentRegistry())
	if err := agent.orchestratorEngine.RegisterWorker(orchestrator.AgentDescriptor{
		ID:           AgentTestWorkflowWorkerID,
		Name:         "test workflow worker",
		Capabilities: []orchestrator.AgentCapability{"chat_model", "tool", "agent_test"},
	}, &workflowNodeWorker{agent: agent}); err != nil {
		return nil, err
	}

	wf, err := buildAgentTestWorkflow()
	if err != nil {
		return nil, err
	}
	if err = agent.orchestratorEngine.RegisterWorkflow(wf); err != nil {
		return nil, err
	}

	return agent, nil
}

func (a *Agent) ProcessInternal(ctx context.Context, taskID string, initialMsg internalproto.Message,
	manager internaltm.Manager) error {
	if len(initialMsg.Parts) == 0 {
		return fmt.Errorf("invalid input parts")
	}
	queryParts := make([]string, 0, len(initialMsg.Parts))
	for _, part := range initialMsg.Parts {
		if part.Type != internalproto.PartTypeText {
			continue
		}
		text := strings.TrimSpace(part.Text)
		if text != "" {
			queryParts = append(queryParts, text)
		}
	}
	if len(queryParts) == 0 {
		return fmt.Errorf("invalid input parts")
	}
	if a.orchestratorEngine == nil {
		return fmt.Errorf("orchestrator engine not initialized")
	}

	ctx = withTaskManager(ctx, manager)
	query := strings.TrimSpace(strings.Join(queryParts, "\n"))

	logger.Infof("[TRACE] agent_test.ProcessInternal start task=%s query_len=%d", taskID, len(query))
	runID, err := a.orchestratorEngine.StartWorkflow(ctx, AgentTestWorkflowID, map[string]any{
		"task_id": taskID,
		"query":   query,
	})
	if err != nil {
		return fmt.Errorf("failed to start agent_test workflow: %w", err)
	}
	logger.Infof("[TRACE] agent_test.ProcessInternal started task=%s run_id=%s", taskID, runID)
	runResult, err := a.orchestratorEngine.WaitRun(ctx, runID)
	if err != nil {
		return fmt.Errorf("failed to wait agent_test workflow: %w", err)
	}
	logger.Infof("[TRACE] agent_test.ProcessInternal done task=%s run_state=%s err=%s", taskID, runResult.State, runResult.ErrorMessage)
	for _, nr := range runResult.NodeResults {
		logger.Infof("[TRACE] agent_test.ProcessInternal node_result task=%s node=%s state=%s node_task=%s err=%s", taskID, nr.NodeID, nr.State, nr.TaskID, nr.ErrorMsg)
	}
	if runResult.State != orchestrator.RunStateSucceeded {
		if runResult.ErrorMessage != "" {
			return fmt.Errorf("agent_test workflow failed: %s", runResult.ErrorMessage)
		}
		return fmt.Errorf("agent_test workflow failed")
	}
	out, _ := runResult.FinalOutput["response"].(string)
	out = strings.TrimSpace(out)
	if out == "" {
		out = "Workflow executed successfully"
	}
	if manager != nil {
		_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateCompleted, &internalproto.Message{
			Role:  internalproto.MessageRoleAgent,
			Parts: []internalproto.Part{internalproto.NewTextPart(out)},
		})
	}
	return nil
}

func (w *workflowNodeWorker) Execute(ctx context.Context, req orchestrator.ExecutionRequest) (orchestrator.ExecutionResult, error) {
	taskID, _ := req.Payload["task_id"].(string)
	query, _ := req.Payload["query"].(string)
	var (
		response string
		err error
	)
	switch req.NodeType {
	case orchestrator.NodeTypeChatModel:
		response, err = w.agent.callChatModel(ctx, taskID, query, req.NodeConfig)
	case orchestrator.NodeTypeTool:
		response, err = w.agent.callTool(ctx, taskID, query, req.NodeConfig)
	default:
		response = strings.TrimSpace(query)
		if response == "" {
			response = "ok"
		}
	}
	if err != nil {
		return orchestrator.ExecutionResult{}, err
	}
	return orchestrator.ExecutionResult{Output: map[string]any{"response": response}}, nil
}

func (a *Agent) callChatModel(ctx context.Context, taskID string, query string, nodeCfg map[string]any) (string, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return "", fmt.Errorf("query is empty")
	}
	baseURL := strings.TrimSpace(a.llmClient.BaseURL)
	apiKey := strings.TrimSpace(a.llmClient.APIKey)
	model := strings.TrimSpace(a.chatModel)
	if nodeCfg != nil {
		if v, ok := nodeCfg["url"].(string); ok && strings.TrimSpace(v) != "" {
			baseURL = strings.TrimSpace(v)
		}
		if v, ok := nodeCfg["apikey"].(string); ok && strings.TrimSpace(v) != "" {
			apiKey = strings.TrimSpace(v)
		}
		if v, ok := nodeCfg["model"].(string); ok && strings.TrimSpace(v) != "" {
			model = strings.TrimSpace(v)
		}
	}
	logger.Infof("[TRACE] agent_test.chatmodel start task=%s model=%s url=%s api_key_set=%t query_len=%d", taskID, model, baseURL, apiKey != "", len(query))
	if baseURL == "" || model == "" {
		return "", fmt.Errorf("chat_model config missing url/model")
	}
	resp, err := llm.NewClient(baseURL, apiKey).ChatCompletion(ctx, model, []llm.Message{{Role: "user", Content: query}}, nil, nil)
	if err != nil {
		return "", err
	}
	resp = strings.TrimSpace(resp)
	if resp == "" {
		resp = "(empty LLM response)"
	}
	logger.Infof("[TRACE] agent_test.chatmodel done task=%s resp_len=%d", taskID, len(resp))
	return resp, nil
}

func (a *Agent) callTool(ctx context.Context, taskID string, query string, nodeCfg map[string]any) (string, error) {
	toolName := ""
	if nodeCfg != nil {
		if v, ok := nodeCfg["tool_name"].(string); ok {
			toolName = strings.TrimSpace(v)
		}
	}
	if toolName == "" {
		return "", fmt.Errorf("tool node missing config.tool_name")
	}
	params := map[string]any{}
	if nodeCfg != nil {
		if m, ok := nodeCfg["input_mapping"].(map[string]any); ok {
			for targetKey, sourceKey := range m {
				src, _ := sourceKey.(string)
				src = strings.TrimSpace(src)
				if src == "query" {
					params[targetKey] = strings.TrimSpace(query)
					continue
				}
				if src == "task_id" {
					params[targetKey] = taskID
					continue
				}
			}
		}
		if m, ok := nodeCfg["params"].(map[string]any); ok {
			for k, v := range m {
				if _, exists := params[k]; !exists {
					params[k] = v
				}
			}
		}
	}
	if _, ok := params["query"]; !ok {
		params["query"] = strings.TrimSpace(query)
	}
	if _, ok := params["task_id"]; !ok {
		params["task_id"] = taskID
	}
	if strings.EqualFold(toolName, "tavily") {
		q, _ := params["query"].(string)
		rawQ := q
		if i := strings.LastIndex(q, "=== 当前问题 ==="); i >= 0 {
			q = strings.TrimSpace(q[i+len("=== 当前问题 ==="):])
		}
		if i := strings.LastIndex(q, "用户:"); i >= 0 {
			q = strings.TrimSpace(q[i+len("用户:"):])
		}
		if q == "" {
			q = strings.TrimSpace(rawQ)
		}
		if len(q) > 400 {
			q = q[:400]
		}
		params["query"] = q
		logger.Infof("[TRACE] agent_test.tavily request task=%s query_len=%d query=%q", taskID, len(q), q)
	}
	tool, err := a.findToolByName(toolName)
	if err != nil {
		return "", err
	}
	out, err := tool.Execute(ctx, params)
	if err != nil {
		return "", err
	}
	resp := strings.TrimSpace(fmt.Sprintf("%v", out))
	if resp == "" {
		resp = "(empty tool response)"
	}
	return resp, nil
}

func (a *Agent) findToolByName(name string) (tools.Tool, error) {
	switch strings.TrimSpace(name) {
	case "tavily":
		if a.TavilyTool == nil {
			return nil, fmt.Errorf("tool tavily is not initialized")
		}
		return a.TavilyTool, nil
	case "amap":
		if a.AmapTool == nil {
			return nil, fmt.Errorf("tool amap is not initialized")
		}
		return a.AmapTool, nil
	case "agent_info":
		if a.AgentInfoTool == nil {
			return nil, fmt.Errorf("tool agent_info is not initialized")
		}
		return a.AgentInfoTool, nil
	case "jina_reader":
		if a.JinaReaderTool == nil {
			return nil, fmt.Errorf("tool jina_reader is not initialized")
		}
		return a.JinaReaderTool, nil
	default:
		return nil, fmt.Errorf("tool %s not found", name)
	}
}

func withTaskManager(ctx context.Context, m internaltm.Manager) context.Context {
	if ctx == nil || m == nil {
		return ctx
	}
	return context.WithValue(ctx, ctxKeyTaskManager{}, m)
}

func taskManagerFromContext(ctx context.Context) internaltm.Manager {
	if ctx == nil {
		return nil
	}
	m, _ := ctx.Value(ctxKeyTaskManager{}).(internaltm.Manager)
	return m
}

func buildAgentTestWorkflow() (*orchestrator.Workflow, error) {
	wf, err := orchestrator.NewWorkflow(AgentTestWorkflowID, "test default workflow")
	if err != nil {
		return nil, err
	}

	if err = wf.AddNode(orchestrator.Node{ID: "N1", Type: orchestrator.NodeTypeStart}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_22f561", Type: orchestrator.NodeTypeChatModel, AgentID: AgentTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "结合用户输入，给出关键检索词", Config: map[string]any{"apikey": "sk-5796edd8954b4227971d376c9007a699", "model": "qwen3.5-flash", "url": "https://dashscope.aliyuncs.com/compatible-mode/v1/"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_fc29e6", Type: orchestrator.NodeTypeTool, AgentID: AgentTestWorkflowWorkerID, TaskType: "agent_test_default", Config: map[string]any{"input_mapping": map[string]any{"query": "N_22f561"}, "params": map[string]any{"api_key": "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", "max_results": "5", "search_depth": "basic"}, "tool_name": "tavily"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_b1943f", Type: orchestrator.NodeTypeChatModel, AgentID: AgentTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "整理搜索结果，结构化整合信息。", Config: map[string]any{"apikey": "sk-5796edd8954b4227971d376c9007a699", "model": "qwen3.5-flash", "url": "https://dashscope.aliyuncs.com/compatible-mode/v1/"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_fcf470", Type: orchestrator.NodeTypeEnd}); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N1", "N_22f561", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N_22f561", "N_fc29e6", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N_fc29e6", "N_b1943f", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N_b1943f", "N_fcf470", "", nil); err != nil {
		return nil, err
	}
	return wf, nil
}
