@startchen
title 工作流相关实体 E-R 图

left to right direction

entity "workflow" as Workflow {
  "id" as wf_id <<key>>
  "name" as wf_name
  "user_id" as wf_user_id
  "start_node_id" as wf_start_node_id
  "created_at" as wf_created_at
}

entity "workflow_node" as WorkflowNode {
  "id" as wn_id <<key>>
  "workflow_id" as wn_workflow_id
  "node_id" as wn_node_id
  "node_type" as wn_node_type
  "name" as wn_name
}

entity "workflow_edge" as WorkflowEdge {
  "id" as we_id <<key>>
  "workflow_id" as we_workflow_id
  "edge_id" as we_edge_id
  "source_node_id" as we_source_node_id
  "target_node_id" as we_target_node_id
}

relationship "包含节点" as HasNode {
}

relationship "包含连线" as HasEdge {
}

Workflow -1- HasNode
HasNode -N- WorkflowNode

Workflow -1- HasEdge
HasEdge -N- WorkflowEdge

@endchen