@startchen
title 用户与工具类实体 E-R 图

left to right direction

entity "users" as Users {
  id
  user_id
  username
  display_name
  status
}

entity "user_tool" as UserTool {
  id
  tool_id
  user_id
  name
  tool_type
  config
  parameters
  output_parameters
}

relationship "创建" as CreateTool {
}

Users -1- CreateTool
CreateTool -N- UserTool

@endchen