@startchen
title 用户与角色实体 E-R 图

left to right direction

entity "users" as Users {
  "id" as u_id <<key>>
  "user_id" as u_user_id
  "username" as u_username
  "display_name" as u_display_name
  "status" as u_status
}

entity "role" as Role {
  "id" as r_id <<key>>
  "role_code" as r_role_code
  "role_name" as r_role_name
  "status" as r_status
}

relationship "分配" as Assign {
}

Users -N- Assign
Assign -1- Role

@endchen