//go:build reference
// +build reference

package tools

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/cloudwego/eino/components/tool"
	"github.com/cloudwego/eino/components/tool/utils"
)

type TavilyConfig struct {
	APIKey     string
	HTTPClient *http.Client
}

func NewTavilyClient(_ context.Context, config *TavilyConfig) (*TavilyClient, error) {
	if config == nil {
		config = &TavilyConfig{}
	}
	if err := config.validate(); err != nil {
		return nil, err
	}
	return &TavilyClient{
		config: config,
	}, nil
}

func NewTavily(ctx context.Context, config *TavilyConfig) ([]tool.BaseTool, error) {
	tt, err := NewTavilyClient(ctx, config)
	if err != nil {
		return nil, fmt.Errorf("failed to create ddg search tool: %w", err)
	}

	searchToolName := "tavily-search"
	searchToolDesc := `A powerful web search tool that provides comprehensive, real-time results using Tavily's AI search engine. 
Returns relevant web content with customizable parameters for result count, content type, and domain filtering. 
Ideal for gathering current information, news, and detailed web content analysis.`

	searchTool, err := utils.InferTool(searchToolName, searchToolDesc, tt.Search)
	if err != nil {
		return nil, fmt.Errorf("failed to infer tool: %w", err)
	}

	return []tool.BaseTool{&ToolWrapper{Tool: searchTool}}, nil
}

// validate validates the configuration and sets default values if not provided.
func (conf *TavilyConfig) validate() error {
	if conf == nil {
		return fmt.Errorf("config is nil")
	}
	if conf.APIKey == "" {
		return fmt.Errorf("apikey is nil")
	}
	if conf.HTTPClient == nil {
		conf.HTTPClient = &http.Client{Timeout: time.Second * 10}
	}
	return nil
}

type TavilyClient struct {
	config *TavilyConfig
}

type SearchRequest struct {
	Query                    string      `json:"query" jsonschema_description:"required,description=The query to run a search on."`
	SearchDepth              string      `json:"search_depth,omitempty" jsonschema_description:"enum=basic,enum=advanced,description=The depth of the search. 'advanced' search is tailored to retrieve the most relevant sources and content snippets for your query, while 'basic' search provides generic content snippets from each source. Default: basic"`
	Topic                    string      `json:"topic,omitempty" jsonschema_description:"enum=general,enum=news,description=The category of the search. Determines which agent will be used. Must be 'general' or 'news'. Default: general"`
	Days                     int         `json:"days,omitempty" jsonschema_description:"description=The number of days back from the current date to include in the results. Available only when using the 'news' topic. Default: 7"`
	TimeRange                string      `json:"time_range,omitempty" jsonschema_description:"description=The time range back from the current date. Accepted values include 'day', 'week', 'month', 'year' or shorthand values 'd', 'w', 'm', 'y'."`
	MaxResults               int         `json:"max_results,omitempty" jsonschema_description:"description=The maximum number of search results to return. It must be between 0 and 20. Default: 5"`
	ChunksPerSource          int         `json:"chunks_per_source,omitempty" jsonschema_description:"description=The number of content chunks to retrieve from each source. Each chunk’s length is maximum 500 characters. It must be between 1 and 3. Available only when search_depth is advanced. Default: 3"`
	IncludeImages            bool        `json:"include_images,omitempty" jsonschema_description:"description=Include a list of query-related images in the response. Default: false"`
	IncludeImageDescriptions bool        `json:"include_image_descriptions,omitempty" jsonschema_description:"description=Include a list of query-related images and their descriptions in the response. Default: false"`
	IncludeAnswer            interface{} `json:"include_answer,omitempty" jsonschema_description:"description=Include an answer to the query generated by an LLM based on search results. A 'basic' (or True) answer is quick but less detailed; an 'advanced' answer is more detailed. Default: false"`
	IncludeRawContent        bool        `json:"include_raw_content,omitempty" jsonschema_description:"description=Include the cleaned and parsed HTML content of each search result. Default: false"`
	IncludeDomains           []string    `json:"include_domains,omitempty" jsonschema_description:"description=A list of domains to specifically include in the search results. Default: []"`
	ExcludeDomains           []string    `json:"exclude_domains,omitempty" jsonschema_description:"description=A list of domains to specifically exclude from the search results. Default: []"`
	Timeout                  int         `json:"timeout,omitempty" jsonschema_description:"description=A timeout to be used in requests to the Tavily API. Default: 60"`
}

// SearchResponse 表示搜索响应的结构体
type SearchResponse struct {
	Results      []Result        `json:"results" jsonschema_description:"A list of sorted search results ranked by relevancy."`
	Query        string          `json:"query" jsonschema_description:"Your search query."`
	ResponseTime float64         `json:"response_time" jsonschema_description:"Your search result response time."`
	Answer       *string         `json:"answer,omitempty" jsonschema_description:"The answer to your search query, generated by an LLM based on Tavily’s search results. This is only available if include_answer is set to True."`
	Images       json.RawMessage `json:"images,omitempty" jsonschema_description:"This is only available if include_images is set to True. A list of query - related image URLs. If include_image_descriptions is set to True, each entry will be an ImageResult."`
}

func (response *SearchResponse) String() string {
	bodyBytes, _ := json.Marshal(response)
	return string(bodyBytes)
}

// Result 表示单个搜索结果的结构体
type Result struct {
	Title         string  `json:"title" jsonschema_description:"The title of the search result."`
	URL           string  `json:"url" jsonschema_description:"The URL of the search result."`
	Content       string  `json:"content" jsonschema_description:"The most query - related content from the scraped URL. Tavily uses proprietary AI to extract the most relevant content based on context quality and size."`
	Score         float64 `json:"score" jsonschema_description:"The relevance score of the search result."`
	RawContent    *string `json:"raw_content,omitempty" jsonschema_description:"The parsed and cleaned HTML content of the site. This is only available if include_raw_content is set to True."`
	PublishedDate *string `json:"published_date,omitempty" jsonschema_description:"The publication date of the source. This is only available if the search topic is set to 'news'."`
}

// ImageResult 表示包含描述的图片结果的结构体
type ImageResult struct {
	URL         string `json:"url" jsonschema_description:"The URL of the image."`
	Description string `json:"description" jsonschema_description:"An LLM - generated description of the image."`
}

type ErrorResponse struct {
	Detail struct {
		Error string `json:"error"`
	} `json:"detail"`
}

func (cli *TavilyClient) Search(ctx context.Context, request *SearchRequest) (*SearchResponse, error) {
	requestBodyBytes, err := json.Marshal(request)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.tavily.com/search", bytes.NewBuffer(requestBodyBytes))
	if err != nil {
		return nil, fmt.Errorf("new request: %w", err)
	}
	httpReq.Header.Set("Authorization", "Bearer "+cli.config.APIKey)
	httpReq.Header.Set("Content-Type", "application/json")

	httpRsp, err := cli.config.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do http fail: %w", err)
	}
	defer httpRsp.Body.Close()

	if httpRsp.StatusCode >= http.StatusMultipleChoices {
		responseBodyBytes, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return nil, fmt.Errorf("read http body fail: %w", err)
		}
		errorResponse := &ErrorResponse{}
		if err = json.Unmarshal(responseBodyBytes, errorResponse); err != nil {
			return nil, fmt.Errorf("unmarshal body fail: %w", err)
		}
		return nil, fmt.Errorf("http stats not ok: %s, code: %d, detail: %s",
			httpRsp.Status, httpRsp.StatusCode, errorResponse.Detail)
	}
	responseBodyBytes, err := io.ReadAll(httpRsp.Body)
	if err != nil {
		return nil, fmt.Errorf("read http body fail: %w", err)
	}
	searchResponse := &SearchResponse{}
	if err = json.Unmarshal(responseBodyBytes, searchResponse); err != nil {
		return nil, fmt.Errorf("unmarshal body fail: %w", err)
	}
	return searchResponse, nil
}
