CREATE TABLE IF NOT EXISTS `monitor_run` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `run_id` VARCHAR(128) NOT NULL COMMENT '运行ID',
    `workflow_id` VARCHAR(64) NOT NULL COMMENT '工作流ID',
    `user_id` VARCHAR(128) NOT NULL COMMENT '用户ID',
    `source_agent_id` VARCHAR(64) DEFAULT NULL COMMENT '源Agent ID',
    `task_id` VARCHAR(128) DEFAULT NULL COMMENT '任务ID',
    `status` VARCHAR(32) NOT NULL COMMENT '运行状态',
    `started_at` DATETIME NOT NULL COMMENT '开始时间',
    `finished_at` DATETIME DEFAULT NULL COMMENT '结束时间',
    `duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '总耗时(毫秒)',
    `current_node_id` VARCHAR(64) DEFAULT NULL COMMENT '当前节点ID',
    `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
    `alert_count` INT NOT NULL DEFAULT 0 COMMENT '告警数量',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_monitor_run_id` (`run_id`),
    KEY `idx_monitor_run_workflow_id` (`workflow_id`),
    KEY `idx_monitor_run_task_id` (`task_id`),
    KEY `idx_monitor_run_status` (`status`),
    KEY `idx_monitor_run_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流运行监控摘要表';

CREATE TABLE IF NOT EXISTS `monitor_event` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `event_id` VARCHAR(128) NOT NULL COMMENT '事件ID',
    `run_id` VARCHAR(128) NOT NULL COMMENT '运行ID',
    `task_id` VARCHAR(128) DEFAULT NULL COMMENT '任务ID',
    `workflow_id` VARCHAR(64) NOT NULL COMMENT '工作流ID',
    `user_id` VARCHAR(128) NOT NULL COMMENT '用户ID',
    `agent_id` VARCHAR(64) DEFAULT NULL COMMENT 'Agent ID',
    `node_id` VARCHAR(64) DEFAULT NULL COMMENT '节点ID',
    `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型',
    `status` VARCHAR(32) NOT NULL COMMENT '状态',
    `message` VARCHAR(1024) DEFAULT NULL COMMENT '事件消息',
    `input_snapshot` TEXT DEFAULT NULL COMMENT '输入摘要',
    `output_snapshot` TEXT DEFAULT NULL COMMENT '输出摘要',
    `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
    `duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '耗时(毫秒)',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_monitor_event_id` (`event_id`),
    KEY `idx_monitor_event_run_id` (`run_id`),
    KEY `idx_monitor_event_workflow_id` (`workflow_id`),
    KEY `idx_monitor_event_node_id` (`node_id`),
    KEY `idx_monitor_event_type` (`event_type`),
    KEY `idx_monitor_event_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流执行事件日志表';

CREATE TABLE IF NOT EXISTS `monitor_alert` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `alert_id` VARCHAR(128) NOT NULL COMMENT '告警ID',
    `run_id` VARCHAR(128) NOT NULL COMMENT '运行ID',
    `workflow_id` VARCHAR(64) NOT NULL COMMENT '工作流ID',
    `agent_id` VARCHAR(64) DEFAULT NULL COMMENT 'Agent ID',
    `node_id` VARCHAR(64) DEFAULT NULL COMMENT '节点ID',
    `alert_type` VARCHAR(64) NOT NULL COMMENT '告警类型',
    `severity` VARCHAR(32) NOT NULL COMMENT '告警级别',
    `title` VARCHAR(255) NOT NULL COMMENT '告警标题',
    `content` TEXT DEFAULT NULL COMMENT '告警详情',
    `status` VARCHAR(32) NOT NULL DEFAULT 'open' COMMENT '告警状态',
    `triggered_at` DATETIME NOT NULL COMMENT '触发时间',
    `resolved_at` DATETIME DEFAULT NULL COMMENT '恢复时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_monitor_alert_id` (`alert_id`),
    KEY `idx_monitor_alert_run_id` (`run_id`),
    KEY `idx_monitor_alert_workflow_id` (`workflow_id`),
    KEY `idx_monitor_alert_node_id` (`node_id`),
    KEY `idx_monitor_alert_status` (`status`),
    KEY `idx_monitor_alert_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流监控告警表';
