// Code generated by codegen. DO NOT EDIT.
// Generated at: 2026-04-04T09:00:41+08:00

package operator_test

import (
	"ai/config"
	"ai/pkg/llm"
	"ai/pkg/monitor"
	"ai/pkg/orchestrator"
	internalproto "ai/pkg/protocol"
	"ai/pkg/storage"
	internaltm "ai/pkg/taskmanager"
	"ai/pkg/tools"
	"context"
	"fmt"
	"strings"
	"time"
)

const (
	OperatorTestWorkflowID = "operator test"
	OperatorTestWorkflowWorkerID = "operator test_worker"
	OperatorTestDefaultTaskType = "operator test_default"
)

type ctxKeyTaskManager struct{}

var OperatorTestNodeTypeByID = map[string]string{
	"N1": "start",
	"判断": "chatmodel",
	"循环": "loop",
	"整理": "chatmodel",
	"提取": "chatmodel",
	"分支": "condition",
	"搜索": "tool",
	"结束": "end",
}

type Agent struct {
	orchestratorEngine orchestrator.Engine
	llmClient          *llm.Client
	chatModel          string
	FetchTool tools.Tool
	MysqlExecTool tools.Tool
	AgentInfoTool tools.Tool
	AmapTool tools.Tool
	AkshareOneMcpTool tools.Tool
	JsonFileTool tools.Tool
	ScriptExecTool tools.Tool
	JinaReaderTool tools.Tool
	TavilyTool tools.Tool
}

type workflowNodeWorker struct {
	agent *Agent
}

type stepReporter struct {
	agent string
	taskID string
	manager internaltm.Manager
}

func NewAgent() (*Agent, error) {
	cfg := config.GetMainConfig()
	agent := &Agent{}

	agent.llmClient = llm.NewClient(cfg.LLM.URL, cfg.LLM.APIKey)
	agent.chatModel = strings.TrimSpace(cfg.LLM.ChatModel)
	if agent.chatModel == "" {
		agent.chatModel = strings.TrimSpace(cfg.LLM.ReasoningModel)
	}
	if agent.chatModel == "" {
		agent.chatModel = "qwen3-235b-a22b"
	}
	FetchToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "auto",
	}
	agent.FetchTool = tools.NewMCPTool("fetch", "本地 Fetch MCP 服务；由 Agent 通过 tool_name 决定具体子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 MCP 子工具名"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "MCP 子工具参数对象；优先使用此字段作为调用参数"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，将 query 等普通参数直接透传"},}, FetchToolConfig)
	MysqlExecToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "mysql_exec",
	}
	agent.MysqlExecTool = tools.NewMCPTool("mysql_exec", "本地 MySQL MCP 服务；执行任意 SQL", []tools.ToolParameter{{Name: "sql", Type: tools.ParamTypeString, Required: true, Description: "要执行的 SQL 语句"},}, MysqlExecToolConfig)
	AgentInfoToolConfig := tools.HTTPToolConfig{
		Method: "GET",
		URL: "http://127.0.0.1:8080/v1/orchestrator/agents",
		Timeout: time.Duration(30) * time.Second,
	}
	agent.AgentInfoTool = tools.NewHTTPTool("agent_info", "查询当前系统可用的 Agent 列表与能力说明", []tools.ToolParameter{}, AgentInfoToolConfig)
	AmapToolConfig := tools.MCPToolConfig{
		ServerURL: "https://mcp.amap.com/sse?key=603b7b141042d9e7418bd3617c1758c2",
		ToolName: "auto",
	}
	agent.AmapTool = tools.NewMCPTool("amap", "调用 AMap MCP 服务；由 Agent 通过 tool_name 决定具体子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 MCP 子工具名（如 maps_direction_driving）"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "MCP 子工具参数对象；优先使用此字段作为调用参数"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，将 query 等普通参数直接透传"},}, AmapToolConfig)
	AkshareOneMcpToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "auto",
	}
	agent.AkshareOneMcpTool = tools.NewMCPTool("akshare-one-mcp", "本地 AkShare MCP 服务；由 Agent 通过 tool_name 决定具体子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 MCP 子工具名"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "MCP 子工具参数对象；优先使用此字段作为调用参数"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，将 query 等普通参数直接透传"},}, AkshareOneMcpToolConfig)
	JsonFileToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "json_file",
	}
	agent.JsonFileTool = tools.NewMCPTool("json_file", "本地 JSON 文件读写 MCP 服务", []tools.ToolParameter{{Name: "action", Type: tools.ParamTypeString, Required: true, Description: "read 或 write"},{Name: "path", Type: tools.ParamTypeString, Required: true, Description: "JSON 文件路径"},{Name: "json", Type: tools.ParamTypeObject, Required: false, Description: "写入时的 JSON 内容，可传对象或 JSON 字符串"},}, JsonFileToolConfig)
	ScriptExecToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "script_exec",
	}
	agent.ScriptExecTool = tools.NewMCPTool("script_exec", "本地脚本执行 MCP 服务", []tools.ToolParameter{{Name: "path", Type: tools.ParamTypeString, Required: true, Description: "脚本路径或命令"},{Name: "args", Type: tools.ParamTypeArray, Required: false, Description: "命令参数数组"},{Name: "interpreter", Type: tools.ParamTypeString, Required: false, Description: "可选解释器，如 powershell/python"},{Name: "cwd", Type: tools.ParamTypeString, Required: false, Description: "执行工作目录"},{Name: "timeout_sec", Type: tools.ParamTypeNumber, Required: false, Description: "超时时间秒，默认 60"},}, ScriptExecToolConfig)
	JinaReaderToolConfig := tools.HTTPToolConfig{
		Method: "GET",
		URL: "https://r.jina.ai/{{url}}",
		Timeout: time.Duration(60) * time.Second,
	}
	agent.JinaReaderTool = tools.NewHTTPTool("jina_reader", "通过 Jina Reader 拉取并清洗网页正文内容", []tools.ToolParameter{{Name: "url", Type: tools.ParamTypeString, Required: true, Description: "需要读取的网页地址（http/https）"},}, JinaReaderToolConfig)
	TavilyToolConfig := tools.HTTPToolConfig{
		Method: "POST",
		URL: "https://api.tavily.com/search",
		Timeout: time.Duration(30) * time.Second,
	}
	TavilyToolConfig.Headers = map[string]string{
		"Content-Type": "application/json",
		"Authorization": "Bearer {{api_key}}",
	}
	TavilyToolConfig.BodyTemplate = "{\"query\":\"{{query}}\",\"search_depth\":\"{{search_depth}}\",\"max_results\":{{max_results}}}"
	agent.TavilyTool = tools.NewHTTPTool("tavily", "调用 Tavily 搜索 API 进行实时检索", []tools.ToolParameter{{Name: "api_key", Type: tools.ParamTypeString, Required: true, Description: "Tavily API Key"},{Name: "query", Type: tools.ParamTypeString, Required: true, Description: "检索关键词"},{Name: "search_depth", Type: tools.ParamTypeString, Required: false, Description: "检索深度，可选 basic/advanced"},{Name: "max_results", Type: tools.ParamTypeNumber, Required: false, Description: "返回结果数量上限"},}, TavilyToolConfig)

	engineCfg := orchestrator.Config{
		DefaultTaskTimeoutSec: cfg.Orchestrator.DefaultTaskTimeoutSec,
		RetryMaxAttempts:      cfg.Orchestrator.Retry.MaxAttempts,
		RetryBaseBackoffMs:    cfg.Orchestrator.Retry.BaseBackoffMs,
		RetryMaxBackoffMs:     cfg.Orchestrator.Retry.MaxBackoffMs,
	}
	if engineCfg.DefaultTaskTimeoutSec <= 0 {
		engineCfg.DefaultTaskTimeoutSec = 600
	}
	if engineCfg.RetryMaxAttempts <= 0 {
		engineCfg.RetryMaxAttempts = 3
	}
	if engineCfg.RetryBaseBackoffMs <= 0 {
		engineCfg.RetryBaseBackoffMs = 200
	}
	if engineCfg.RetryMaxBackoffMs <= 0 {
		engineCfg.RetryMaxBackoffMs = 5000
	}
	mysqlStorage, mysqlErr := storage.GetMySQLStorage()
	if (mysqlErr != nil || mysqlStorage == nil) && strings.TrimSpace(cfg.MySQL.DSN) != "" {
		mysqlStorage, mysqlErr = storage.InitMySQL(strings.TrimSpace(cfg.MySQL.DSN))
	}
	if mysqlErr == nil && mysqlStorage != nil {
		engineCfg.MonitorService = monitor.NewService(mysqlStorage, nil)
	} else {
	}

	agent.orchestratorEngine = orchestrator.NewEngine(engineCfg, orchestrator.NewInMemoryAgentRegistry())
	if err := agent.orchestratorEngine.RegisterWorker(orchestrator.AgentDescriptor{
		ID:           OperatorTestWorkflowWorkerID,
		Name:         "operator test workflow worker",
		Capabilities: []orchestrator.AgentCapability{"chat_model", "tool", "operator test"},
	}, &workflowNodeWorker{agent: agent}); err != nil {
		return nil, err
	}

	wf, err := buildOperatorTestWorkflow()
	if err != nil {
		return nil, err
	}
	if err = agent.orchestratorEngine.RegisterWorkflow(wf); err != nil {
		return nil, err
	}

	return agent, nil
}

func (a *Agent) ProcessInternal(ctx context.Context, taskID string, initialMsg internalproto.Message,
	manager internaltm.Manager) error {
	if len(initialMsg.Parts) == 0 {
		return fmt.Errorf("invalid input parts")
	}
	queryParts := make([]string, 0, len(initialMsg.Parts))
	for _, part := range initialMsg.Parts {
		if part.Type != internalproto.PartTypeText {
			continue
		}
		text := strings.TrimSpace(part.Text)
		if text != "" {
			queryParts = append(queryParts, text)
		}
	}
	if len(queryParts) == 0 {
		return fmt.Errorf("invalid input parts")
	}
	if a.orchestratorEngine == nil {
		return fmt.Errorf("orchestrator engine not initialized")
	}

	ctx = withTaskManager(ctx, manager)
	query := strings.TrimSpace(strings.Join(queryParts, "\n"))

	userID := ""
	if initialMsg.Metadata != nil {
		userID = strings.TrimSpace(fmt.Sprint(initialMsg.Metadata["user_id"]))
		if userID == "" || userID == "<nil>" {
			userID = strings.TrimSpace(fmt.Sprint(initialMsg.Metadata["userId"]))
		}
		if userID == "" || userID == "<nil>" {
			userID = strings.TrimSpace(fmt.Sprint(initialMsg.Metadata["UserID"]))
		}
		if userID == "<nil>" {
			userID = ""
		}
	}

	runID, err := a.orchestratorEngine.StartWorkflow(ctx, OperatorTestWorkflowID, map[string]any{
		"task_id": taskID,
		"query":   query,
		"text":    query,
		"input":   query,
		"user_id": userID,
		"source_agent_id": "operator test",
		"agent_id": "operator test",
	})
	if err != nil {
		return fmt.Errorf("failed to start operator test workflow: %w", err)
	}
	stopProgress := a.startProgressReporter(ctx, taskID, runID, manager)
	defer stopProgress()
	runResult, err := a.orchestratorEngine.WaitRun(ctx, runID)
	if err != nil {
		return fmt.Errorf("failed to wait operator test workflow: %w", err)
	}
	if runResult.State != orchestrator.RunStateSucceeded {
		if runResult.ErrorMessage != "" {
			return fmt.Errorf("operator test workflow failed: %s", runResult.ErrorMessage)
		}
		return fmt.Errorf("operator test workflow failed")
	}
	out, _ := runResult.FinalOutput["response"].(string)
	out = strings.TrimSpace(out)
	if out == "" {
		out = "Workflow executed successfully"
	}
	if manager != nil {
		_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateCompleted, &internalproto.Message{
			Role:  internalproto.MessageRoleAgent,
			Parts: []internalproto.Part{internalproto.NewTextPart(out)},
		})
	}
	return nil
}

func (w *workflowNodeWorker) Execute(ctx context.Context, req orchestrator.ExecutionRequest) (orchestrator.ExecutionResult, error) {
	taskID, _ := req.Payload["task_id"].(string)
	query, _ := req.Payload["query"].(string)
	var (
		response string
		err error
	)
	switch req.NodeType {
	case orchestrator.NodeTypeChatModel:
		response, err = w.agent.callChatModel(ctx, taskID, query, req.NodeConfig)
	case orchestrator.NodeTypeTool:
		response, err = w.agent.callTool(ctx, taskID, query, req.NodeConfig)
	default:
		response = strings.TrimSpace(query)
		if response == "" {
			response = "ok"
		}
	}
	if err != nil {
		return orchestrator.ExecutionResult{}, err
	}
	return orchestrator.ExecutionResult{Output: map[string]any{"response": response}}, nil
}

func (a *Agent) callChatModel(ctx context.Context, taskID string, query string, nodeCfg map[string]any) (string, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return "", fmt.Errorf("query is empty")
	}
	baseURL := strings.TrimSpace(a.llmClient.BaseURL)
	apiKey := strings.TrimSpace(a.llmClient.APIKey)
	model := strings.TrimSpace(a.chatModel)
	if nodeCfg != nil {
		if v, ok := nodeCfg["url"].(string); ok && strings.TrimSpace(v) != "" {
			baseURL = strings.TrimSpace(v)
		}
		if v, ok := nodeCfg["apikey"].(string); ok && strings.TrimSpace(v) != "" {
			apiKey = strings.TrimSpace(v)
		}
		if v, ok := nodeCfg["model"].(string); ok && strings.TrimSpace(v) != "" {
			model = strings.TrimSpace(v)
		}
	}
	if baseURL == "" || model == "" {
		return "", fmt.Errorf("chat_model config missing url/model")
	}
	resp, err := llm.NewClient(baseURL, apiKey).ChatCompletion(ctx, model, []llm.Message{{Role: "user", Content: query}}, nil, nil)
	if err != nil {
		return "", err
	}
	resp = strings.TrimSpace(resp)
	if resp == "" {
		resp = "(empty LLM response)"
	}
	return resp, nil
}

func (a *Agent) callTool(ctx context.Context, taskID string, query string, nodeCfg map[string]any) (string, error) {
	toolName := ""
	if nodeCfg != nil {
		if v, ok := nodeCfg["tool_name"].(string); ok {
			toolName = strings.TrimSpace(v)
		}
	}
	if toolName == "" {
		return "", fmt.Errorf("tool node missing config.tool_name")
	}
	params := map[string]any{}
	if nodeCfg != nil {
		if m, ok := nodeCfg["input_mapping"].(map[string]any); ok {
			for targetKey, sourceKey := range m {
				src, _ := sourceKey.(string)
				src = strings.TrimSpace(src)
				if src == "query" {
					params[targetKey] = strings.TrimSpace(query)
					continue
				}
				if src == "task_id" {
					params[targetKey] = taskID
					continue
				}
			}
		}
		if m, ok := nodeCfg["params"].(map[string]any); ok {
			for k, v := range m {
				if _, exists := params[k]; !exists {
					params[k] = v
				}
			}
		}
	}
	if _, ok := params["query"]; !ok {
		params["query"] = strings.TrimSpace(query)
	}
	if _, ok := params["task_id"]; !ok {
		params["task_id"] = taskID
	}
	if strings.EqualFold(toolName, "tavily") {
		q, _ := params["query"].(string)
		rawQ := q
		if i := strings.LastIndex(q, "=== 褰撳墠闂 ==="); i >= 0 {
			q = strings.TrimSpace(q[i+len("=== 褰撳墠闂 ==="):])
		}
		if i := strings.LastIndex(q, "鐢ㄦ埛:"); i >= 0 {
			q = strings.TrimSpace(q[i+len("鐢ㄦ埛:"):])
		}
		if q == "" {
			q = strings.TrimSpace(rawQ)
		}
		if len(q) > 400 {
			q = q[:400]
		}
		params["query"] = q
	}
	tool, err := a.findToolByName(toolName)
	if err != nil {
		return "", err
	}
	out, err := tool.Execute(ctx, params)
	if err != nil {
		return "", err
	}
	resp := strings.TrimSpace(fmt.Sprintf("%v", out))
	if resp == "" {
		resp = "(empty tool response)"
	}
	return resp, nil
}

func (a *Agent) findToolByName(name string) (tools.Tool, error) {
	switch strings.TrimSpace(name) {
	case "fetch":
		if a.FetchTool == nil {
			return nil, fmt.Errorf("tool fetch is not initialized")
		}
		return a.FetchTool, nil
	case "mysql_exec":
		if a.MysqlExecTool == nil {
			return nil, fmt.Errorf("tool mysql_exec is not initialized")
		}
		return a.MysqlExecTool, nil
	case "agent_info":
		if a.AgentInfoTool == nil {
			return nil, fmt.Errorf("tool agent_info is not initialized")
		}
		return a.AgentInfoTool, nil
	case "amap":
		if a.AmapTool == nil {
			return nil, fmt.Errorf("tool amap is not initialized")
		}
		return a.AmapTool, nil
	case "akshare-one-mcp":
		if a.AkshareOneMcpTool == nil {
			return nil, fmt.Errorf("tool akshare-one-mcp is not initialized")
		}
		return a.AkshareOneMcpTool, nil
	case "json_file":
		if a.JsonFileTool == nil {
			return nil, fmt.Errorf("tool json_file is not initialized")
		}
		return a.JsonFileTool, nil
	case "script_exec":
		if a.ScriptExecTool == nil {
			return nil, fmt.Errorf("tool script_exec is not initialized")
		}
		return a.ScriptExecTool, nil
	case "jina_reader":
		if a.JinaReaderTool == nil {
			return nil, fmt.Errorf("tool jina_reader is not initialized")
		}
		return a.JinaReaderTool, nil
	case "tavily":
		if a.TavilyTool == nil {
			return nil, fmt.Errorf("tool tavily is not initialized")
		}
		return a.TavilyTool, nil
	default:
		return nil, fmt.Errorf("tool %s not found", name)
	}
}

func withTaskManager(ctx context.Context, m internaltm.Manager) context.Context {
	if ctx == nil || m == nil {
		return ctx
	}
	return context.WithValue(ctx, ctxKeyTaskManager{}, m)
}

func taskManagerFromContext(ctx context.Context) internaltm.Manager {
	if ctx == nil {
		return nil
	}
	m, _ := ctx.Value(ctxKeyTaskManager{}).(internaltm.Manager)
	return m
}

func (a *Agent) buildNodeProgressMessage(nodeID string, stepState internalproto.StepState) string {
	nodeID = strings.TrimSpace(nodeID)
	nodeType := "node"
	if v := strings.TrimSpace(OperatorTestNodeTypeByID[nodeID]); v != "" {
		nodeType = v
	}
	_ = stepState
	return fmt.Sprintf("鑺傜偣鍚?%s 鑺傜偣绫诲瀷:%s", nodeID, nodeType)
}

func (a *Agent) startProgressReporter(ctx context.Context, taskID string, runID string, manager internaltm.Manager) func() {
	if manager == nil || a.orchestratorEngine == nil {
		return func() {}
	}
	stopCh := make(chan struct{})
	doneCh := make(chan struct{})
	go func() {
		defer close(doneCh)
		ticker := time.NewTicker(200 * time.Millisecond)
		defer ticker.Stop()
		started := map[string]bool{}
		finished := map[string]bool{}
		for {
			run, err := a.orchestratorEngine.GetRun(ctx, runID)
			if err == nil {
				nodeID := strings.TrimSpace(run.CurrentNodeID)
				if nodeID != "" && !started[nodeID] {
					started[nodeID] = true
					messageZh := a.buildNodeProgressMessage(nodeID, internalproto.StepStateStart)
					ev := internalproto.NewStepEvent("operator test", "workflow", nodeID, internalproto.StepStateStart, messageZh)
					text := messageZh
					if token, tokenErr := internalproto.EncodeStepToken(ev); tokenErr == nil {
						text = messageZh + "\n" + token
					}
					_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateWorking, &internalproto.Message{
						Role:  internalproto.MessageRoleAgent,
						Parts: []internalproto.Part{internalproto.NewTextPart(text)},
					})
				}
				for _, nr := range run.NodeResults {
					id := strings.TrimSpace(nr.NodeID)
					if id == "" || finished[id] {
						continue
					}
					stepState, ok := generatedToTerminalStepState(nr.State)
					if !ok {
						continue
					}
					finished[id] = true
					messageZh := a.buildNodeProgressMessage(id, stepState)
					ev := internalproto.NewStepEvent("operator test", "workflow", id, stepState, messageZh)
					if token, tokenErr := internalproto.EncodeStepToken(ev); tokenErr == nil {
						text := messageZh + "\n" + token
						_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateWorking, &internalproto.Message{
							Role:  internalproto.MessageRoleAgent,
							Parts: []internalproto.Part{internalproto.NewTextPart(text)},
						})
					}
				}
				if run.State != orchestrator.RunStateRunning {
					return
				}
			}
			select {
			case <-ctx.Done():
				return
			case <-stopCh:
				return
			case <-ticker.C:
			}
		}
	}()
	return func() {
		close(stopCh)
		<-doneCh
	}
}

func generatedToTerminalStepState(state orchestrator.TaskState) (internalproto.StepState, bool) {
	switch state {
	case orchestrator.TaskStateSucceeded:
		return internalproto.StepStateEnd, true
	case orchestrator.TaskStateFailed, orchestrator.TaskStateCanceled:
		return internalproto.StepStateError, true
	default:
		return "", false
	}
}

func buildOperatorTestWorkflow() (*orchestrator.Workflow, error) {
	wf, err := orchestrator.NewWorkflow(OperatorTestWorkflowID, "operator test default workflow")
	if err != nil {
		return nil, err
	}

	if err = wf.AddNode(orchestrator.Node{ID: "N1", Type: orchestrator.NodeTypeStart, Config: map[string]any{"input_source": "previous"}, Metadata: map[string]string{"next_to": "循环", "ui.agent": "orchestrator", "ui.label": "开始", "ui.x": "120", "ui.y": "121"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "判断", Type: orchestrator.NodeTypeChatModel, AgentID: OperatorTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "根据当前检索结果判断是否已经足够回答用户问题。仅输出 true 或 false。", Config: map[string]any{"apikey": "sk-5796edd8954b4227971d376c9007a699", "input_source": "history", "input_type": "string", "model": "qwen3.5-35b-a3b", "output_type": "string", "url": "https://dashscope.aliyuncs.com/compatible-mode/v1/"}, Metadata: map[string]string{"next_to": "分支", "ui.agent": "custom", "ui.label": "模型推理", "ui.x": "542", "ui.y": "8"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "循环", Type: orchestrator.NodeTypeLoop, Metadata: map[string]string{"ui.agent": "custom", "ui.label": "循环", "ui.x": "377", "ui.y": "204"}, LoopConfig: &orchestrator.LoopConfig{MaxIterations: 5, ContinueTo: "判断", ExitTo: "整理"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "整理", Type: orchestrator.NodeTypeChatModel, AgentID: OperatorTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "根据当前检索结果整理输出为结构化内容。当前结果: ", Config: map[string]any{"apikey": "sk-5796edd8954b4227971d376c9007a699", "input_source": "history", "input_type": "string", "model": "qwen3.5-35b-a3b", "output_type": "string", "url": "https://dashscope.aliyuncs.com/compatible-mode/v1/"}, Metadata: map[string]string{"next_to": "结束", "ui.agent": "custom", "ui.label": "模型推理", "ui.x": "711", "ui.y": "215"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "提取", Type: orchestrator.NodeTypeChatModel, AgentID: OperatorTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "请基于用户问题与当前检索结果，提取一个新的检索关键词。只输出关键词。", Config: map[string]any{"apikey": "sk-5796edd8954b4227971d376c9007a699", "input_source": "history", "input_type": "string", "model": "qwen3.5-35b-a3b", "output_type": "string", "url": "https://dashscope.aliyuncs.com/compatible-mode/v1/"}, Metadata: map[string]string{"next_to": "搜索", "ui.agent": "custom", "ui.label": "模型推理", "ui.x": "785", "ui.y": "454"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "分支", Type: orchestrator.NodeTypeCondition, Config: map[string]any{"operator": "eq", "right_type": "bool", "right_value": "true"}, Metadata: map[string]string{"false_to": "提取", "true_to": "整理", "ui.agent": "custom", "ui.label": "条件判断", "ui.x": "834", "ui.y": "18"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "搜索", Type: orchestrator.NodeTypeTool, AgentID: OperatorTestWorkflowWorkerID, TaskType: "operator test_default", Config: map[string]any{"input_mapping": map[string]any{"query": "提取"}, "input_source": "previous", "params": map[string]any{"api_key": "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", "max_results": "5", "search_depth": "basic"}, "tool_name": "tavily"}, Metadata: map[string]string{"next_to": "循环", "ui.agent": "custom", "ui.label": "工具调用", "ui.x": "352", "ui.y": "430"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "结束", Type: orchestrator.NodeTypeEnd, Config: map[string]any{"input_source": "previous"}, Metadata: map[string]string{"next_to": "", "ui.agent": "orchestrator", "ui.label": "结束", "ui.x": "1060", "ui.y": "152"}}); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N1", "循环", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("循环", "判断", "body", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("判断", "分支", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("循环", "整理", "exit", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("整理", "结束", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("分支", "提取", "false", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("提取", "搜索", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("搜索", "循环", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("分支", "整理", "true", nil); err != nil {
		return nil, err
	}
	return wf, nil
}
