// Code generated by codegen. DO NOT EDIT.
// Generated at: 2026-04-14T22:21:12+08:00

package admin_agent_test

import (
	"ai/config"
	"ai/pkg/llm"
	"ai/pkg/monitor"
	"ai/pkg/orchestrator"
	internalproto "ai/pkg/protocol"
	"ai/pkg/storage"
	internaltm "ai/pkg/taskmanager"
	"ai/pkg/tools"
	"context"
	"fmt"
	"strings"
	"time"
)

const (
	AdminAgentTestWorkflowID = "admin agent test"
	AdminAgentTestWorkflowWorkerID = "admin agent test_worker"
	AdminAgentTestDefaultTaskType = "admin agent test_default"
)

type ctxKeyTaskManager struct{}

var AdminAgentTestNodeTypeByID = map[string]string{
	"N1": "start",
	"N_e321d3": "chatmodel",
	"N_f3bae1": "tool",
	"N_8fde1e": "chatmodel",
	"N_d1b4ee": "end",
}

type Agent struct {
	orchestratorEngine orchestrator.Engine
	llmClient          *llm.Client
	chatModel          string
	JinaReaderTool tools.Tool
	MysqlExecTool tools.Tool
	BaziTool tools.Tool
	AkshareOneMcpTool tools.Tool
	AgentInfoTool tools.Tool
	TavilyTool tools.Tool
	AmapTool tools.Tool
	JsonFileTool tools.Tool
	ScriptExecTool tools.Tool
	FetchTool tools.Tool
}

type workflowNodeWorker struct {
	agent *Agent
}

type stepReporter struct {
	agent string
	taskID string
	manager internaltm.Manager
}

func NewAgent() (*Agent, error) {
	cfg := config.GetMainConfig()
	agent := &Agent{}

	agent.llmClient = llm.NewClient(cfg.LLM.URL, cfg.LLM.APIKey)
	agent.chatModel = strings.TrimSpace(cfg.LLM.ChatModel)
	if agent.chatModel == "" {
		agent.chatModel = strings.TrimSpace(cfg.LLM.ReasoningModel)
	}
	if agent.chatModel == "" {
		agent.chatModel = "qwen3.5-plus"
	}
	JinaReaderToolConfig := tools.HTTPToolConfig{
		Method: "GET",
		URL: "https://r.jina.ai/{{url}}",
		Timeout: time.Duration(60) * time.Second,
	}
	agent.JinaReaderTool = tools.NewHTTPTool("jina_reader", "通过 Jina Reader 读取网页正文", []tools.ToolParameter{{Name: "url", Type: tools.ParamTypeString, Required: true, Description: "待读取网页链接，需为 http/https"},}, JinaReaderToolConfig)
	MysqlExecToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "mysql_exec",
	}
	agent.MysqlExecTool = tools.NewMCPTool("mysql_exec", "本地 MySQL MCP 服务，用于执行 SQL", []tools.ToolParameter{{Name: "sql", Type: tools.ParamTypeString, Required: true, Description: "要执行的 SQL 语句"},}, MysqlExecToolConfig)
	BaziToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "auto",
	}
	agent.BaziTool = tools.NewMCPTool("bazi", "本地 Bazi MCP 服务，由 Agent 通过 tool_name 自动决定调用哪个八字子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 Bazi MCP 子工具名"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "Bazi MCP 子工具参数对象，优先使用该字段作为调用参数"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，则 query 等普通参数会被直接透传"},}, BaziToolConfig)
	AkshareOneMcpToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "auto",
	}
	agent.AkshareOneMcpTool = tools.NewMCPTool("akshare-one-mcp", "AkShare MCP 服务，由 Agent 通过 tool_name 自动选择财经子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 AkShare MCP 子工具名"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "AkShare MCP 子工具参数对象，优先使用该字段"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，则 query 等参数会被透传"},}, AkshareOneMcpToolConfig)
	AgentInfoToolConfig := tools.HTTPToolConfig{
		Method: "GET",
		URL: "http://127.0.0.1:8080/v1/orchestrator/agents",
		Timeout: time.Duration(30) * time.Second,
	}
	agent.AgentInfoTool = tools.NewHTTPTool("agent_info", "查询当前系统内可调用的 Agent 列表", []tools.ToolParameter{}, AgentInfoToolConfig)
	TavilyToolConfig := tools.HTTPToolConfig{
		Method: "POST",
		URL: "https://api.tavily.com/search",
		Timeout: time.Duration(30) * time.Second,
	}
	TavilyToolConfig.Headers = map[string]string{
		"Content-Type": "application/json",
		"Authorization": "Bearer {{api_key}}",
	}
	TavilyToolConfig.BodyTemplate = "{\"query\":\"{{query}}\",\"search_depth\":\"{{search_depth}}\",\"max_results\":{{max_results}}}"
	agent.TavilyTool = tools.NewHTTPTool("tavily", "调用 Tavily 搜索 API 执行联网检索", []tools.ToolParameter{{Name: "api_key", Type: tools.ParamTypeString, Required: true, Description: "Tavily API Key"},{Name: "query", Type: tools.ParamTypeString, Required: true, Description: "搜索查询词"},{Name: "search_depth", Type: tools.ParamTypeString, Required: false, Description: "搜索深度 basic 或 advanced", Default: "basic", Enum: []any{"basic", "advanced"}},{Name: "max_results", Type: tools.ParamTypeNumber, Required: false, Description: "最多返回结果数", Default: 5},}, TavilyToolConfig)
	AmapToolConfig := tools.MCPToolConfig{
		ServerURL: "https://mcp.amap.com/sse?key=603b7b141042d9e7418bd3617c1758c2",
		ToolName: "auto",
	}
	agent.AmapTool = tools.NewMCPTool("amap", "AMap MCP 服务，由 Agent 通过 tool_name 自动选择地图子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 AMap MCP 子工具名"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "AMap MCP 子工具参数对象，优先使用该字段"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，则 query 等参数会被透传"},}, AmapToolConfig)
	JsonFileToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "json_file",
	}
	agent.JsonFileTool = tools.NewMCPTool("json_file", "本地 JSON 文件 MCP 服务", []tools.ToolParameter{{Name: "action", Type: tools.ParamTypeString, Required: true, Description: "操作类型，read 或 write"},{Name: "path", Type: tools.ParamTypeString, Required: true, Description: "JSON 文件路径"},{Name: "json", Type: tools.ParamTypeObject, Required: false, Description: "写入时提供的 JSON 对象"},}, JsonFileToolConfig)
	ScriptExecToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "script_exec",
	}
	agent.ScriptExecTool = tools.NewMCPTool("script_exec", "本地脚本执行 MCP 服务", []tools.ToolParameter{{Name: "path", Type: tools.ParamTypeString, Required: true, Description: "脚本路径"},{Name: "args", Type: tools.ParamTypeArray, Required: false, Description: "脚本执行参数"},{Name: "interpreter", Type: tools.ParamTypeString, Required: false, Description: "解释器，可选 powershell 或 python"},{Name: "cwd", Type: tools.ParamTypeString, Required: false, Description: "执行工作目录"},{Name: "timeout_sec", Type: tools.ParamTypeNumber, Required: false, Description: "超时时间，默认 60 秒"},}, ScriptExecToolConfig)
	FetchToolConfig := tools.MCPToolConfig{
		ServerURL: "",
		ToolName: "auto",
	}
	agent.FetchTool = tools.NewMCPTool("fetch", "本地 Fetch MCP 服务，由 Agent 通过 tool_name 自动选择网页相关子工具", []tools.ToolParameter{{Name: "tool_name", Type: tools.ParamTypeString, Required: true, Description: "要调用的 Fetch MCP 子工具名"},{Name: "arguments", Type: tools.ParamTypeObject, Required: false, Description: "Fetch MCP 子工具参数对象，优先使用该字段"},{Name: "query", Type: tools.ParamTypeString, Required: false, Description: "兼容字段；若未提供 arguments，则 query 等参数会被透传"},}, FetchToolConfig)

	engineCfg := orchestrator.Config{
		DefaultTaskTimeoutSec: cfg.Orchestrator.DefaultTaskTimeoutSec,
		RetryMaxAttempts:      cfg.Orchestrator.Retry.MaxAttempts,
		RetryBaseBackoffMs:    cfg.Orchestrator.Retry.BaseBackoffMs,
		RetryMaxBackoffMs:     cfg.Orchestrator.Retry.MaxBackoffMs,
	}
	if engineCfg.DefaultTaskTimeoutSec <= 0 {
		engineCfg.DefaultTaskTimeoutSec = 600
	}
	if engineCfg.RetryMaxAttempts <= 0 {
		engineCfg.RetryMaxAttempts = 3
	}
	if engineCfg.RetryBaseBackoffMs <= 0 {
		engineCfg.RetryBaseBackoffMs = 200
	}
	if engineCfg.RetryMaxBackoffMs <= 0 {
		engineCfg.RetryMaxBackoffMs = 5000
	}
	mysqlStorage, mysqlErr := storage.GetMySQLStorage()
	if (mysqlErr != nil || mysqlStorage == nil) && strings.TrimSpace(cfg.MySQL.DSN) != "" {
		mysqlStorage, mysqlErr = storage.InitMySQL(strings.TrimSpace(cfg.MySQL.DSN))
	}
	if mysqlErr == nil && mysqlStorage != nil {
		engineCfg.MonitorService = monitor.NewService(mysqlStorage, nil)
	} else {
	}

	agent.orchestratorEngine = orchestrator.NewEngine(engineCfg, orchestrator.NewInMemoryAgentRegistry())
	if err := agent.orchestratorEngine.RegisterWorker(orchestrator.AgentDescriptor{
		ID:           AdminAgentTestWorkflowWorkerID,
		Name:         "admin agent test workflow worker",
		Capabilities: []orchestrator.AgentCapability{"chat_model", "tool", "admin agent test"},
	}, &workflowNodeWorker{agent: agent}); err != nil {
		return nil, err
	}

	wf, err := buildAdminAgentTestWorkflow()
	if err != nil {
		return nil, err
	}
	if err = agent.orchestratorEngine.RegisterWorkflow(wf); err != nil {
		return nil, err
	}

	return agent, nil
}

func (a *Agent) ProcessInternal(ctx context.Context, taskID string, initialMsg internalproto.Message,
	manager internaltm.Manager) error {
	if len(initialMsg.Parts) == 0 {
		return fmt.Errorf("invalid input parts")
	}
	queryParts := make([]string, 0, len(initialMsg.Parts))
	for _, part := range initialMsg.Parts {
		if part.Type != internalproto.PartTypeText {
			continue
		}
		text := strings.TrimSpace(part.Text)
		if text != "" {
			queryParts = append(queryParts, text)
		}
	}
	if len(queryParts) == 0 {
		return fmt.Errorf("invalid input parts")
	}
	if a.orchestratorEngine == nil {
		return fmt.Errorf("orchestrator engine not initialized")
	}

	ctx = withTaskManager(ctx, manager)
	query := strings.TrimSpace(strings.Join(queryParts, "\n"))

	userID := ""
	if initialMsg.Metadata != nil {
		userID = strings.TrimSpace(fmt.Sprint(initialMsg.Metadata["user_id"]))
		if userID == "" || userID == "<nil>" {
			userID = strings.TrimSpace(fmt.Sprint(initialMsg.Metadata["userId"]))
		}
		if userID == "" || userID == "<nil>" {
			userID = strings.TrimSpace(fmt.Sprint(initialMsg.Metadata["UserID"]))
		}
		if userID == "<nil>" {
			userID = ""
		}
	}

	runID, err := a.orchestratorEngine.StartWorkflow(ctx, AdminAgentTestWorkflowID, map[string]any{
		"task_id": taskID,
		"query":   query,
		"text":    query,
		"input":   query,
		"user_id": userID,
		"source_agent_id": "admin agent test",
		"agent_id": "admin agent test",
	})
	if err != nil {
		return fmt.Errorf("failed to start admin agent test workflow: %w", err)
	}
	stopProgress := a.startProgressReporter(ctx, taskID, runID, manager)
	defer stopProgress()
	runResult, err := a.orchestratorEngine.WaitRun(ctx, runID)
	if err != nil {
		return fmt.Errorf("failed to wait admin agent test workflow: %w", err)
	}
	if runResult.State != orchestrator.RunStateSucceeded {
		if runResult.ErrorMessage != "" {
			return fmt.Errorf("admin agent test workflow failed: %s", runResult.ErrorMessage)
		}
		return fmt.Errorf("admin agent test workflow failed")
	}
	out, _ := runResult.FinalOutput["response"].(string)
	out = strings.TrimSpace(out)
	if out == "" {
		out = "Workflow executed successfully"
	}
	if manager != nil {
		_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateCompleted, &internalproto.Message{
			Role:  internalproto.MessageRoleAgent,
			Parts: []internalproto.Part{internalproto.NewTextPart(out)},
		})
	}
	return nil
}

func (w *workflowNodeWorker) Execute(ctx context.Context, req orchestrator.ExecutionRequest) (orchestrator.ExecutionResult, error) {
	taskID, _ := req.Payload["task_id"].(string)
	query, _ := req.Payload["query"].(string)
	var (
		response string
		err error
	)
	switch req.NodeType {
	case orchestrator.NodeTypeChatModel:
		response, err = w.agent.callChatModel(ctx, taskID, query, req.NodeConfig)
	case orchestrator.NodeTypeTool:
		response, err = w.agent.callTool(ctx, taskID, query, req.NodeConfig, req.Payload)
	default:
		response = strings.TrimSpace(query)
		if response == "" {
			response = "ok"
		}
	}
	if err != nil {
		return orchestrator.ExecutionResult{}, err
	}
	return orchestrator.ExecutionResult{Output: map[string]any{"response": response}}, nil
}

func (a *Agent) callChatModel(ctx context.Context, taskID string, query string, nodeCfg map[string]any) (string, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return "", fmt.Errorf("query is empty")
	}
	baseURL := strings.TrimSpace(a.llmClient.BaseURL)
	apiKey := strings.TrimSpace(a.llmClient.APIKey)
	model := strings.TrimSpace(a.chatModel)
	if nodeCfg != nil {
		if v, ok := nodeCfg["url"].(string); ok && strings.TrimSpace(v) != "" {
			baseURL = strings.TrimSpace(v)
		}
		if v, ok := nodeCfg["apikey"].(string); ok && strings.TrimSpace(v) != "" {
			apiKey = strings.TrimSpace(v)
		}
		if v, ok := nodeCfg["model"].(string); ok && strings.TrimSpace(v) != "" {
			model = strings.TrimSpace(v)
		}
	}
	if baseURL == "" || model == "" {
		return "", fmt.Errorf("chat_model config missing url/model")
	}
	resp, err := llm.NewClient(baseURL, apiKey).ChatCompletion(ctx, model, []llm.Message{{Role: "user", Content: query}}, nil, nil)
	if err != nil {
		return "", err
	}
	resp = strings.TrimSpace(resp)
	if resp == "" {
		resp = "(empty LLM response)"
	}
	return resp, nil
}

func resolveGeneratedPayloadValue(payload map[string]any, sourceKey string) (any, bool) {
	trimmed := strings.TrimSpace(sourceKey)
	if trimmed == "" || payload == nil {
		return nil, false
	}
	if v, ok := payload[trimmed]; ok {
		return v, true
	}
	parts := strings.Split(trimmed, ".")
	if len(parts) <= 1 {
		return nil, false
	}
	current, ok := payload[parts[0]]
	if !ok {
		return nil, false
	}
	for i := 1; i < len(parts); i++ {
		m, ok := current.(map[string]any)
		if !ok {
			return nil, false
		}
		next, ok := m[parts[i]]
		if !ok {
			return nil, false
		}
		current = next
	}
	return current, true
}

func extractGeneratedStringCandidate(v any, preferredKey string) (string, bool) {
	if s, ok := v.(string); ok {
		return s, true
	}
	if b, ok := v.([]byte); ok {
		return string(b), true
	}
	m, ok := v.(map[string]any)
	if !ok {
		return "", false
	}
	candidateKeys := []string{
		strings.TrimSpace(preferredKey),
		"query",
		"text",
		"content",
		"result",
		"response",
		"body",
		"value",
	}
	for _, k := range candidateKeys {
		if k == "" {
			continue
		}
		if val, exists := m[k]; exists {
			if s, ok := val.(string); ok {
				return s, true
			}
		}
	}
	for _, k := range candidateKeys {
		if k == "" {
			continue
		}
		if val, exists := m[k]; exists {
			if nested, ok := val.(map[string]any); ok {
				if s, ok := nested[preferredKey].(string); ok {
					return s, true
				}
				if s, ok := nested["value"].(string); ok {
					return s, true
				}
			}
		}
	}
	return "", false
}

func normalizeGeneratedToolParams(params map[string]any, defs []tools.ToolParameter) map[string]any {
	if len(params) == 0 || len(defs) == 0 {
		return params
	}
	for _, def := range defs {
		if def.Type != tools.ParamTypeString {
			continue
		}
		val, exists := params[def.Name]
		if !exists || val == nil {
			continue
		}
		if _, ok := val.(string); ok {
			continue
		}
		if normalized, ok := extractGeneratedStringCandidate(val, def.Name); ok {
			params[def.Name] = normalized
		}
	}
	return params
}

func (a *Agent) callTool(ctx context.Context, taskID string, query string, nodeCfg map[string]any, payload map[string]any) (string, error) {
	toolName := ""
	if nodeCfg != nil {
		if v, ok := nodeCfg["tool_name"].(string); ok {
			toolName = strings.TrimSpace(v)
		}
	}
	if toolName == "" {
		return "", fmt.Errorf("tool node missing config.tool_name")
	}
	params := map[string]any{}
	if nodeCfg != nil {
		if m, ok := nodeCfg["input_mapping"].(map[string]any); ok {
			for targetKey, sourceKey := range m {
				src, _ := sourceKey.(string)
				src = strings.TrimSpace(src)
				if src == "query" {
					params[targetKey] = strings.TrimSpace(query)
					continue
				}
				if src == "task_id" {
					params[targetKey] = taskID
					continue
				}
				if val, exists := resolveGeneratedPayloadValue(payload, src); exists {
					if normalized, ok := extractGeneratedStringCandidate(val, targetKey); ok {
						val = normalized
					} else if _, isMap := val.(map[string]any); isMap && payload != nil {
						if fallback, fallbackOK := payload[targetKey]; fallbackOK {
							if _, fallbackIsMap := fallback.(map[string]any); !fallbackIsMap {
								val = fallback
							}
						}
					}
					params[targetKey] = val
					continue
				}
			}
		}
		if m, ok := nodeCfg["params"].(map[string]any); ok {
			for k, v := range m {
				if _, exists := params[k]; !exists {
					params[k] = v
				}
			}
		}
	}
	if _, ok := params["query"]; !ok {
		params["query"] = strings.TrimSpace(query)
	}
	if _, ok := params["task_id"]; !ok {
		params["task_id"] = taskID
	}
	if strings.EqualFold(toolName, "tavily") {
		q, _ := params["query"].(string)
		rawQ := q
		if i := strings.LastIndex(q, "=== 褰撳墠闂 ==="); i >= 0 {
			q = strings.TrimSpace(q[i+len("=== 褰撳墠闂 ==="):])
		}
		if i := strings.LastIndex(q, "鐢ㄦ埛:"); i >= 0 {
			q = strings.TrimSpace(q[i+len("鐢ㄦ埛:"):])
		}
		if q == "" {
			q = strings.TrimSpace(rawQ)
		}
		if len(q) > 400 {
			q = q[:400]
		}
		params["query"] = q
	}
	tool, err := a.findToolByName(toolName)
	if err != nil {
		return "", err
	}
	params = normalizeGeneratedToolParams(params, tool.Info().Parameters)
	out, err := tool.Execute(ctx, params)
	if err != nil {
		return "", err
	}
	resp := strings.TrimSpace(fmt.Sprintf("%v", out))
	if resp == "" {
		resp = "(empty tool response)"
	}
	return resp, nil
}

func (a *Agent) findToolByName(name string) (tools.Tool, error) {
	switch strings.TrimSpace(name) {
	case "jina_reader":
		if a.JinaReaderTool == nil {
			return nil, fmt.Errorf("tool jina_reader is not initialized")
		}
		return a.JinaReaderTool, nil
	case "mysql_exec":
		if a.MysqlExecTool == nil {
			return nil, fmt.Errorf("tool mysql_exec is not initialized")
		}
		return a.MysqlExecTool, nil
	case "bazi":
		if a.BaziTool == nil {
			return nil, fmt.Errorf("tool bazi is not initialized")
		}
		return a.BaziTool, nil
	case "akshare-one-mcp":
		if a.AkshareOneMcpTool == nil {
			return nil, fmt.Errorf("tool akshare-one-mcp is not initialized")
		}
		return a.AkshareOneMcpTool, nil
	case "agent_info":
		if a.AgentInfoTool == nil {
			return nil, fmt.Errorf("tool agent_info is not initialized")
		}
		return a.AgentInfoTool, nil
	case "tavily":
		if a.TavilyTool == nil {
			return nil, fmt.Errorf("tool tavily is not initialized")
		}
		return a.TavilyTool, nil
	case "amap":
		if a.AmapTool == nil {
			return nil, fmt.Errorf("tool amap is not initialized")
		}
		return a.AmapTool, nil
	case "json_file":
		if a.JsonFileTool == nil {
			return nil, fmt.Errorf("tool json_file is not initialized")
		}
		return a.JsonFileTool, nil
	case "script_exec":
		if a.ScriptExecTool == nil {
			return nil, fmt.Errorf("tool script_exec is not initialized")
		}
		return a.ScriptExecTool, nil
	case "fetch":
		if a.FetchTool == nil {
			return nil, fmt.Errorf("tool fetch is not initialized")
		}
		return a.FetchTool, nil
	default:
		return nil, fmt.Errorf("tool %s not found", name)
	}
}

func withTaskManager(ctx context.Context, m internaltm.Manager) context.Context {
	if ctx == nil || m == nil {
		return ctx
	}
	return context.WithValue(ctx, ctxKeyTaskManager{}, m)
}

func taskManagerFromContext(ctx context.Context) internaltm.Manager {
	if ctx == nil {
		return nil
	}
	m, _ := ctx.Value(ctxKeyTaskManager{}).(internaltm.Manager)
	return m
}

func (a *Agent) buildNodeProgressMessage(nodeID string, stepState internalproto.StepState) string {
	nodeID = strings.TrimSpace(nodeID)
	nodeType := "node"
	if v := strings.TrimSpace(AdminAgentTestNodeTypeByID[nodeID]); v != "" {
		nodeType = v
	}
	_ = stepState
	return fmt.Sprintf("节点名称:%s 节点类型:%s", nodeID, nodeType)
}

func (a *Agent) startProgressReporter(ctx context.Context, taskID string, runID string, manager internaltm.Manager) func() {
	if manager == nil || a.orchestratorEngine == nil {
		return func() {}
	}
	stopCh := make(chan struct{})
	doneCh := make(chan struct{})
	go func() {
		defer close(doneCh)
		ticker := time.NewTicker(200 * time.Millisecond)
		defer ticker.Stop()
		started := map[string]bool{}
		finished := map[string]bool{}
		for {
			run, err := a.orchestratorEngine.GetRun(ctx, runID)
			if err == nil {
				nodeID := strings.TrimSpace(run.CurrentNodeID)
				if nodeID != "" && !started[nodeID] {
					started[nodeID] = true
					messageZh := a.buildNodeProgressMessage(nodeID, internalproto.StepStateStart)
					ev := internalproto.NewStepEvent("admin agent test", "workflow", nodeID, internalproto.StepStateStart, messageZh)
					text := messageZh
					if token, tokenErr := internalproto.EncodeStepToken(ev); tokenErr == nil {
						text = messageZh + "\n" + token
					}
					_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateWorking, &internalproto.Message{
						Role:  internalproto.MessageRoleAgent,
						Parts: []internalproto.Part{internalproto.NewTextPart(text)},
					})
				}
				for _, nr := range run.NodeResults {
					id := strings.TrimSpace(nr.NodeID)
					if id == "" || finished[id] {
						continue
					}
					stepState, ok := generatedToTerminalStepState(nr.State)
					if !ok {
						continue
					}
					finished[id] = true
					messageZh := a.buildNodeProgressMessage(id, stepState)
					ev := internalproto.NewStepEvent("admin agent test", "workflow", id, stepState, messageZh)
					if token, tokenErr := internalproto.EncodeStepToken(ev); tokenErr == nil {
						text := messageZh + "\n" + token
						_ = manager.UpdateTaskState(ctx, taskID, internalproto.TaskStateWorking, &internalproto.Message{
							Role:  internalproto.MessageRoleAgent,
							Parts: []internalproto.Part{internalproto.NewTextPart(text)},
						})
					}
				}
				if run.State != orchestrator.RunStateRunning {
					return
				}
			}
			select {
			case <-ctx.Done():
				return
			case <-stopCh:
				return
			case <-ticker.C:
			}
		}
	}()
	return func() {
		close(stopCh)
		<-doneCh
	}
}

func generatedToTerminalStepState(state orchestrator.TaskState) (internalproto.StepState, bool) {
	switch state {
	case orchestrator.TaskStateSucceeded:
		return internalproto.StepStateEnd, true
	case orchestrator.TaskStateFailed, orchestrator.TaskStateCanceled:
		return internalproto.StepStateError, true
	default:
		return "", false
	}
}

func buildAdminAgentTestWorkflow() (*orchestrator.Workflow, error) {
	wf, err := orchestrator.NewWorkflow(AdminAgentTestWorkflowID, "admin agent test default workflow")
	if err != nil {
		return nil, err
	}

	if err = wf.AddNode(orchestrator.Node{ID: "N1", Type: orchestrator.NodeTypeStart, Config: map[string]any{"input_source": "previous"}, Metadata: map[string]string{"next_to": "N_e321d3", "ui.agent": "orchestrator", "ui.label": "开始", "ui.x": "120", "ui.y": "120"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_e321d3", Type: orchestrator.NodeTypeChatModel, AgentID: AdminAgentTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "请基于用户问题，提取一个新的检索关键词。只输出关键词。", Config: map[string]any{"input_source": "previous", "input_type": "string", "output_type": "string"}, Metadata: map[string]string{"next_to": "N_f3bae1", "ui.agent": "custom", "ui.label": "模型推理", "ui.x": "371", "ui.y": "128"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_f3bae1", Type: orchestrator.NodeTypeTool, AgentID: AdminAgentTestWorkflowWorkerID, TaskType: "admin agent test_default", Config: map[string]any{"input_mapping": map[string]any{"query": "N_e321d3"}, "input_source": "previous", "params": map[string]any{"api_key": "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"}, "tool_name": "tavily"}, Metadata: map[string]string{"next_to": "N_8fde1e", "ui.agent": "custom", "ui.label": "工具调用", "ui.x": "629", "ui.y": "131"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_8fde1e", Type: orchestrator.NodeTypeChatModel, AgentID: AdminAgentTestWorkflowWorkerID, TaskType: "chat_model", PreInput: "根据当前检索结果整理输出为结构化内容。当前结果: ", Config: map[string]any{"input_source": "previous", "input_type": "string", "output_type": "string"}, Metadata: map[string]string{"next_to": "N_d1b4ee", "ui.agent": "custom", "ui.label": "模型推理", "ui.x": "888", "ui.y": "125"}}); err != nil {
		return nil, err
	}
	if err = wf.AddNode(orchestrator.Node{ID: "N_d1b4ee", Type: orchestrator.NodeTypeEnd, Config: map[string]any{"input_source": "previous"}, Metadata: map[string]string{"next_to": "", "ui.agent": "orchestrator", "ui.label": "结束", "ui.x": "1134", "ui.y": "180"}}); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N1", "N_e321d3", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N_e321d3", "N_f3bae1", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N_f3bae1", "N_8fde1e", "", nil); err != nil {
		return nil, err
	}
	if err = wf.AddEdgeWithLabel("N_8fde1e", "N_d1b4ee", "", nil); err != nil {
		return nil, err
	}
	return wf, nil
}
